[[quiz]]
# 6502667c-cccd-439a-aa89-35fd141647b6
name = "サヨナラから始まる物語"
description = '''
<style>
.hidden {
  display: none;
}

.container {
  display: flex;
  justify-content: space-between;
}

.right {
  display: flex;
  align-items: center;
  flex-direction: column;
  max-width: 50%;
}
.right img {
  object-fit: contain;
  justify-content: space-between;
}
</style>

<div class="container">
<div>

<code><pre>
每题的题号都是一个 UUID
大部分 UUID 是 36 位带横线的格式，但也有部分是 32 位无横线
两种格式都可以正常解析
答案正确即可进入下一题，否则会 404
除第一题之外，之后的每一题的网页里都会有一个红包口令
<!-- Alipay{就像这样} -->
</pre></code>

<span class="hidden">2</span>ねえ、偶然ってなんだっけ？　必然ってなんだっけ？<br>
<span class="hidden">f</span>君といると分からなくなるよ<br>
<span class="hidden">b</span>Ah　夢みたいな感動も　出会いの日の衝動も<br>
<span class="hidden">4</span>当たり前のように引き寄せたね<br><br>

<span class="hidden">5</span>運命のいたずらに　気づかずにわたしたち<br>
<span class="hidden">5</span>ずっと傍にいたとか　なんだか可笑しいね<br><br>

<span class="hidden">2</span>めぐり逢えた奇跡の真ん中で<br>
<span class="hidden">d</span>少しくらいわたし泣いたっていいよね<br>
<span class="hidden">8</span>サヨナラから始まる物語<br>
<span class="hidden">2</span>胸の奥に刺さった切なさが痛いけど<br>
<span class="hidden">6</span>駆け出したら　いつでもそこがスタートライン<br>
<span class="hidden">a</span>君と(君と)　走って行こう　デスティニー<br><br>

<span class="hidden">4</span>Ah　月が夜を告げて　太陽が朝を呼ぶ<br>
<span class="hidden">e</span>そしてまた『一日』になっていく<br><br>

<span class="hidden">2</span>追いかけっこするように　星が交差する街<br>
<span class="hidden">8</span>あっという間だったね　積み上げた季節<br><br>

<span class="hidden">8</span>たどり着いたステージの裏側で<br>
<span class="hidden">e</span>いつも君が優しく笑ってたんだね<br>
<span class="hidden">f</span>サヨナラから生まれた物語<br>
<span class="hidden">4</span>言えなかった言葉がまだたくさんあるよ<br>
<span class="hidden">9</span>溢れすぎた心からは本音がこぼれた<br>
<span class="hidden">1</span>もうちょっと(もうちょっと)　消えないでいて　デスティニー<br>
<span class="hidden">1</span>Ah　デスティニー<br><br>

<span class="hidden">a</span>たった一つ　わがまま言っていいかな<br>
<span class="hidden">7</span>『生まれ変わっても傍にいてくれますか？』<br><br>

<span class="hidden">1</span>めぐり逢えた奇跡の真ん中で<br>
<span class="hidden">9</span>少しくらいわたし泣いたっていいよね<br>
<span class="hidden">b</span>サヨナラから始まる物語<br>
<span class="hidden">2</span>胸の奥に刺さった切なさが痛いけど<br>
<span class="hidden">7</span>駆け出したら　いつでもそこがスタートライン<br>
<span class="hidden">1</span>君と(君と)　走って行こう　デスティニー
<span class="hidden">a</span>
</div>

<div class="right">
  <iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=1490357828&auto=1&height=66"></iframe>
  <img src="https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/97/1e/08/971e0839-eccd-428a-f870-9877ccb04155/source/800x800bb.jpg" />
</div>

</div>
'''

[[quiz]]
# 2fb4552d-826a-4e28-8ef4-911a719b271a
name = "MOLE"
description = '''
<!-- Alipay{2fb4552d826a4e28} 1.14*30 -->
小 Q 从数字音乐商店 MOLE 上下载了一首歌曲准备分享给朋友，但他不知道的是 flag 也被分享出去了，为什么呢？ 
'''
links = [{ name = "下载（密码是本题的 UUID）", url = "https://file.mmf.moe/s/vjFy" }]

[[quiz]]
# c4504de9-942c-4612-b542-c95336af37b9
name = "Touch The Flag"
description = '''
<!-- Alipay{c4504de9942c4612} 5.14*15 -->
<pre><code>
环境每隔 5 分钟重置一次。
</code></pre>

可以让我摸摸你的 Flag 吗？
'''
links = [{ name = "Link", url = "https://touch.triangle-2022.mmf.moe" }]

[[quiz]]
# 8b27526d-a5cf-4f21-8d15-d0fa4da81005
name = "Minyami"
description = '''
<!-- Alipay{8b27526da5cf4f21} *8 -->
好不容易下到了 flag，但却加了 --nomerge，怎么办？？？
'''
links = [{ name = "下载（密码是本题的 UUID）", url = "https://file.mmf.moe/s/XKse" }]

[[quiz]]
# bd01774d-f4a1-475f-aec3-8f5019c489ee
name = "新年快乐！"
description = '''
<!-- Alipay{bd01774df4a1475f} *5 -->
今年的新年红包就到这里了（x <br>
从大二就开始想准备的新年红包在大四寒假终于摸出来了，感叹<br><br>

「サヨナラから始まる物語」是签到，希望大家都去看看 IDOLY PRIDE<br>
「MOLE」是在研究完 FLAC 格式之后想到的，为了增加难度把加密方式塞进了 vendor string 里<br>
「Touch The Flag」是在研究 Rust 的 vfs 实现时发现的，只能说实现得很神秘<br>
「Minyami」是一次偶然没法合并的时候出现的，jxw 什么时候加个输出 segment 顺序的功能啊（罪大恶极<br><br>

最后给&nbsp;<a href="https://book.anni.rs/">Project Anni</a>&nbsp;打个广告，是一个 Self Host 的 Airsonic 替代品，有兴趣的可以来群里摸鱼（<br>
'''
links = [{ name = "Link", url = "https://t.me/+lFJHji4gCZc2N2M1" }]
